---
title: "Final Grade Reflection"
author: "Caleb Jensen"
format: pdf
editor: visual
---

## Final Grade Reflection

After a quarter of learning and hard work I believe I have earned the grade of an A in STAT 331, a claim which I will attempt to back in this paper. First, looking at gaining proficiency of the learning targets. I demonstrated proficiency in WD-1 in Lab 4 challenge, question 1) reading in the data. WD-2 can be seen in Lab 4 Challenge question 2) clean home data and Lab 3 question 9) demographic data. WD-3 is demonstrated in practice activity 5, question 1); as well as in Lab 3, questions 12, 13, and 14. WD-4 is evidenced in Lab 5, questions 9 and 10; Lab 4 Challenge questions 2; Lab 6, question 5; and 3; and Practice Activity 5, question 1. WD-5 is seen in Lab 4 Challenge question 3 as well as in Preview Activity -- Reshaping Data, questions 5, 6, and 7. WD-6 is demonstrated in Lab 4, questions 5, 6, and 7 as well as in Lab 4 Challenge, question 3. WD-7 is in Lab 4, questions 6 and 7 as well as in Lab 6, question 5. R-1 is seen in Lab 4 and Lab 4 Challenge. R-2 is shown in Lab 3 and Lab 4 Challenge. R-3 is apparent in Lab 6, question 4; Lab 8, question 2; Lab 3, question 9; and Lab 4, question 5. DVS-1 is seen in Lab 4, questions 6 and 7 as well as Lab 5, questions 7, 8, and 9. DVS-2 is shown in Lab 4, question 7, Lab 4 Challenge, question 3; and Lab 9 Challenge, question 5. DVS-3 is shown in Lab 5, questions 5, 6, and 7; additionally in Lab 3, question 10 and Lab 6, question 3. DVS-4 is shown in Lab 3, question 11, Lab 4, questions 5, 6, and 7. DVS-5 is present in Lab 6, questions 2 and 6 as well as Lab 3 Challenge, question 3. DVS-6 is shown in Lab 9 Challenge question 6. DVS-7 can be seen in Lab 9 Challenge, question 2. PE-2 is accomplished in Lab 3 Challenge, question 3 and Lab 6, question 6. PE-2 is in Lab 6, question 4 and 6 as well as in Lab 8, question 6. PE-3 can be seen in Lab 3 challenge, question 3, Lab 6, question 2, 4, and 6. PE-4 is shown in Lab 4 Challenge, question 2 and 3 as well as Lab 3, questions 11, 12, and 13. DSM-1 is seen in Preview Activity 9, questions 6, 7, and 8. Finally, DSM-2 can be seen in Lab 9 Challenge, question 3. I had many opportunities to revise my code this quarter. In the beginning of the quarter my quarto documents often included long outputs from reading in data or packages from a failure to use #\| output: false. However, by lab 4 I was consistently producing readable and professional looking reports. Another example of continued learning is in Lab 3. On my first attempt I used about 8 statements to carry out the same operation on multiple columns. After reading peer reviews and feedback from Professor Theobold I was able to use an across statement to make my code more efficient, easier to read, and less repetitive. I also demonstrated revised thinking in Lab 4. In this Lab I originally used a bar chart to represent the price difference between two different types of avocados. However, in the feedback it was pointed out that this is poor data science practice, so I changed the chart to a point chart to show the same information. I used this in later labs including lab 5 questions 5, 6, and 7. I also had the opportunity to challenge myself consistently throughout the year. One example of this is in Lab 4 Challenge where I was able to find multiple years of housing data, clean it, and join it to the avocados data. After doing this I was able to create a colored chart to look at the price of homes and avocados in different communities. I also took the opportunity to use annotations rather than legends multiple times including in Lab 4 question 6. I also challenged myself working with strings, one of the areas I lacked the most in. I was able to use regular expressions in Lab 8 Challenge to make line breaks after each stanza of the 12 days of Christmas as well as to add \", and\" to the last line of each stanza. This is probably the area in the most this quarter, simply because I had so little experience in it before. I was not a perfect team member, but I tried to be helpful and cooperative. This was the only class I never skipped and I frequently asked questions of Dr. Theobald. I could not attend office hours normally due to other classes, but I was able to go to virtual office hours on Fridays if I or the team needed help. I really enjoyed being part of my team and felt that, especially in class, we worked very well together, asked and answered questions together, and overall participated in building each other up. Finally, I attempted to give positive, constructive feedback to my peers on their code. In order to do this I needed to turn in the majority of my labs on time so I could be assigned a peer review. I managed to do this almost every week. I tried to offer good feedback both on items done well and things to work on either with efficiency or with tidy coding conventions. One good example of this is my peer review for Harshini\'s Lab 2. I attempted to give good feedback on all peer reviews but this is probably the area of the course I was most lacking in. However, that being said I believe I have earned an A in this course. I enjoyed the material and feel much better prepared to work with data cleaning and preparing it before looking at relationships and models.