---
title: "Lab 8"
author: "Caleb Jensen"
format: 
  html: 
    self-contained: true
editor: visual
---

## 1)

```{r}
#| output: false
library(dplyr)
library(glue)
library(stringr)
library(purrr)
```

## 2)

```{r}
xmas <- read.csv("https://www.dropbox.com/s/e584pryn8evm1gz/xmas.csv?dl=1")
```

## 3)

```{r}
pluralize_gift <- function(gift){

gift <- gift |> 
  str_c("s", sep = "") |> 
  str_replace("ys$", "ies") |> 
  str_replace("oo[:alpha:]+", "eese")

return(gift)

}
```

## 4) 

```{r}
make_phrase <- function(num_word, item, verb, adjective, location) {
  
  ## Step 1: Replace NAs with blank strings
  num_word <- str_replace_na(num_word, "")
  verb <- str_replace_na(verb, "")
  item <- str_replace_na(item, "")
  adjective <- str_replace_na(adjective, "")
  location <- str_replace_na(location, "")
  
  ## Step 2: If the day is larger than 1, the items need pluralized! 
  item <- if_else(num_word != "one", 
          pluralize_gift(item), 
          item)
  
  ## Step 3: If the word starts with a vowel, add "an" to the beginning
  num_word <- if_else(num_word != "one", 
          num_word, 
          "a")
  item <- str_replace_all(item, "^[aeiou]", "an \1")
  
  
  
  ## Step 4: Glue all of the pieces together! 
  phrase <- glue::glue("{num_word} {adjective} {item} {verb} {location}")
  return(phrase)

}
```

## 5)

```{r}
xmas2 <- xmas %>%
  mutate(day.num = as.character(english::english(Day)
                                ), 
    Full.Phrase = pmap_chr(
      list(
           num_word = day.num,
           item = Gift.Item,
           verb = Verb,
           adjective = Adjective,
           location = Location),
      make_phrase
      )
  )
xmas2$Full.Phrase
```

## 6)

```{r}
sing_line <- function(df, line, phrase_col){
  
  # Step 1: Setup the intro line
  num_word <- english::ordinal(line)
  
  intro <- glue::glue("On the {num_word} day of Christmas my true love gave to me:")
  
  # Step 2: Sing the gift phrases

    phrases <- df |>
      pull( {{phrase_col}} )
    
  ## put it together
  phrases <- str_c(phrases[line:1], sep = "")
  
  phrases <- c(intro, phrases)
  song_day <- if_else(line != 1,  glue::glue_collapse(phrases, sep = "\n", last = "and\n"), glue::glue_collapse(phrases, sep = "\n"))
  return(song_day)

}  

xmas2 |> 
  sing_line(line = 2, phrase_col = Full.Phrase)
```

## 7)

```{r}
map_chr(1:12, ~ sing_line(xmas2, .x, Full.Phrase)) |>
  str_c(collapse = ".\n\n") |>
  cat()
```

## 8)

```{r}
xmas2 <- xmas |>
  mutate(
    day.num = as.character(english::english(Day)), 
    Full.Phrase = pmap_chr(.l = list(num_word = day.num, 
                                     item = Gift.Item, 
                                     verb = Verb, 
                                     adjective = Adjective, 
                                     location = Location), 
                           .f = make_phrase)
  )

map_chr(1:12, ~sing_line(xmas2, .x, Full.Phrase)) |>
  str_c(collapse = "\n") |>
  cat()
```
